const studies={
beli:{name:'Beli',label:'01 · DISCOVERY & RANKING',intro:'Rethinking how we discover, rank, and remember a great meal.',focus:'Restaurant discovery and ranking',format:'Competitive analysis, annotated prototypes, and a proposal deck',description:'This study examines the discovery and ranking experience in Beli. The redesign proposal was delivered directly to Beli’s product team, packaging competitive analysis and annotated prototypes into a pitch for specific improvements.',questions:['How can discovery help people find restaurants that fit their taste?','How can ranking interactions be clearer and easier to navigate?'],status:'The original slide deck will be added here.'},
disney:{name:'Disney+',label:'02 · CONTENT DISCOVERY',intro:'Bringing a little more magic to the path from browsing to watching.',focus:'Information hierarchy and browsing workflows',format:'Website redesign prototype',description:'A consumer product teardown and website redesign exploring how the structure of a streaming experience can support clearer content discovery.',questions:['Does the information hierarchy help viewers decide what to watch?','How can a browsing workflow make the next step feel clear?'],status:'The full website redesign will be added here.'},
duolingo:{name:'Duolingo',label:'03 · ONBOARDING & LEARNING',intro:'Exploring the balance between motivation, clarity, and learning.',focus:'Onboarding, consistency, and learning workflows',format:'Design analysis and slide deck',description:'A design teardown examining the experience of getting started and navigating a learning product through simplicity, consistency, and usability.',questions:['How clearly does onboarding introduce the learning experience?','How do interaction patterns help people understand their progress?'],status:'The original slide deck will be added here.'},
trufru:{name:'TruFru',label:'04 · BRAND & SHOPPING',intro:'Translating a playful product into a clearer, more delicious digital experience.',focus:'Brand expression and information hierarchy',format:'Website redesign prototype',description:'A consumer product teardown and website redesign examining how product information and brand personality can work together in a digital experience.',questions:['How quickly can visitors understand the product and its appeal?','How can visual hierarchy make exploration more intuitive?'],status:'The full website redesign will be added here.'}
};
const dialog=document.querySelector('#case-dialog');
document.querySelectorAll('.case-open').forEach(button=>button.addEventListener('click',()=>{const study=studies[button.dataset.case];document.querySelector('#case-content').innerHTML=`<p class="eyebrow">${study.label}</p><h2 id="case-name">${study.name}</h2><p>${study.intro}</p><h3>The study</h3><p>${study.description}</p><h3>Focus</h3><p>${study.focus}</p><h3>Questions explored</h3><ul>${study.questions.map(q=>`<li>${q}</li>`).join('')}</ul><h3>Deliverable</h3><p>${study.format}</p><div class="asset-status"><strong>Case materials coming soon</strong><p>${study.status} The collection cover is an illustrative preview, rather than the final redesign.</p></div>`;dialog.showModal();}));
document.querySelector('.close').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)dialog.close();}});
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>{b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));});document.querySelectorAll('.card').forEach(card=>{card.hidden=button.dataset.filter!=='all'&&card.dataset.type!==button.dataset.filter;});}));
